// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_expand_surv
DataFrame rcpp_expand_surv(DataFrame surv_df, NumericVector p, NumericVector l_p, CharacterVector y_p);
RcppExport SEXP _pssst_rcpp_expand_surv(SEXP surv_dfSEXP, SEXP pSEXP, SEXP l_pSEXP, SEXP y_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type surv_df(surv_dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l_p(l_pSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y_p(y_pSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_expand_surv(surv_df, p, l_p, y_p));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_expand_surv_helper
DataFrame rcpp_expand_surv_helper(DataFrame surv_df, double nindiv, double np);
RcppExport SEXP _pssst_rcpp_expand_surv_helper(SEXP surv_dfSEXP, SEXP nindivSEXP, SEXP npSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type surv_df(surv_dfSEXP);
    Rcpp::traits::input_parameter< double >::type nindiv(nindivSEXP);
    Rcpp::traits::input_parameter< double >::type np(npSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_expand_surv_helper(surv_df, nindiv, np));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_gradient_multi
NumericVector rcpp_gradient_multi(DataFrame x_df, NumericVector log_shapes, NumericVector log_scales, int dist);
RcppExport SEXP _pssst_rcpp_gradient_multi(SEXP x_dfSEXP, SEXP log_shapesSEXP, SEXP log_scalesSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x_df(x_dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_shapes(log_shapesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_scales(log_scalesSEXP);
    Rcpp::traits::input_parameter< int >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_gradient_multi(x_df, log_shapes, log_scales, dist));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_loglik_multi
NumericVector rcpp_loglik_multi(DataFrame x_df, int num_periods, NumericVector log_shapes, NumericVector log_scales, int dist, NumericVector breakpoints, NumericVector par_period_id);
RcppExport SEXP _pssst_rcpp_loglik_multi(SEXP x_dfSEXP, SEXP num_periodsSEXP, SEXP log_shapesSEXP, SEXP log_scalesSEXP, SEXP distSEXP, SEXP breakpointsSEXP, SEXP par_period_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x_df(x_dfSEXP);
    Rcpp::traits::input_parameter< int >::type num_periods(num_periodsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_shapes(log_shapesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_scales(log_scalesSEXP);
    Rcpp::traits::input_parameter< int >::type dist(distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breakpoints(breakpointsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type par_period_id(par_period_idSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_loglik_multi(x_df, num_periods, log_shapes, log_scales, dist, breakpoints, par_period_id));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hazard_integral
double rcpp_hazard_integral(double lower_bound, double upper_bound, double log_shape, NumericVector log_scale_vec, int dist, NumericVector breakpoints);
RcppExport SEXP _pssst_rcpp_hazard_integral(SEXP lower_boundSEXP, SEXP upper_boundSEXP, SEXP log_shapeSEXP, SEXP log_scale_vecSEXP, SEXP distSEXP, SEXP breakpointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lower_bound(lower_boundSEXP);
    Rcpp::traits::input_parameter< double >::type upper_bound(upper_boundSEXP);
    Rcpp::traits::input_parameter< double >::type log_shape(log_shapeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type log_scale_vec(log_scale_vecSEXP);
    Rcpp::traits::input_parameter< int >::type dist(distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breakpoints(breakpointsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_hazard_integral(lower_bound, upper_bound, log_shape, log_scale_vec, dist, breakpoints));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_turnbull
List rcpp_turnbull(int niter, NumericVector t0, NumericVector t1, NumericVector lefttrunc, NumericVector righttrunc, NumericVector weights, NumericVector set_lower, NumericVector set_upper);
RcppExport SEXP _pssst_rcpp_turnbull(SEXP niterSEXP, SEXP t0SEXP, SEXP t1SEXP, SEXP lefttruncSEXP, SEXP righttruncSEXP, SEXP weightsSEXP, SEXP set_lowerSEXP, SEXP set_upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lefttrunc(lefttruncSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type righttrunc(righttruncSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type set_lower(set_lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type set_upper(set_upperSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_turnbull(niter, t0, t1, lefttrunc, righttrunc, weights, set_lower, set_upper));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pssst_rcpp_expand_surv", (DL_FUNC) &_pssst_rcpp_expand_surv, 4},
    {"_pssst_rcpp_expand_surv_helper", (DL_FUNC) &_pssst_rcpp_expand_surv_helper, 3},
    {"_pssst_rcpp_gradient_multi", (DL_FUNC) &_pssst_rcpp_gradient_multi, 4},
    {"_pssst_rcpp_loglik_multi", (DL_FUNC) &_pssst_rcpp_loglik_multi, 7},
    {"_pssst_rcpp_hazard_integral", (DL_FUNC) &_pssst_rcpp_hazard_integral, 6},
    {"_pssst_rcpp_turnbull", (DL_FUNC) &_pssst_rcpp_turnbull, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_pssst(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
