# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_expand_surv <- function(surv_df, p, l_p, y_p) {
    .Call(`_pssst_rcpp_expand_surv`, surv_df, p, l_p, y_p)
}

rcpp_expand_surv_helper <- function(surv_df, nindiv, np) {
    .Call(`_pssst_rcpp_expand_surv_helper`, surv_df, nindiv, np)
}

