# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_expand_surv <- function(surv_df, p, l_p, y_p) {
    .Call(`_pssst_rcpp_expand_surv`, surv_df, p, l_p, y_p)
}

rcpp_expand_surv_helper <- function(surv_df, nindiv, np) {
    .Call(`_pssst_rcpp_expand_surv_helper`, surv_df, nindiv, np)
}

rcpp_gradient_multi <- function(x_df, log_shapes, log_scales, dist) {
    .Call(`_pssst_rcpp_gradient_multi`, x_df, log_shapes, log_scales, dist)
}

rcpp_loglik_multi <- function(x_df, num_periods, log_shapes, log_scales, dist, breakpoints, par_period_id) {
    .Call(`_pssst_rcpp_loglik_multi`, x_df, num_periods, log_shapes, log_scales, dist, breakpoints, par_period_id)
}

rcpp_F_gengamma <- function(x, alpha, beta, gamma, lower_tail, give_log) {
    .Call(`_pssst_rcpp_F_gengamma`, x, alpha, beta, gamma, lower_tail, give_log)
}

rcpp_f_gengamma <- function(x, alpha, beta, gamma, log_pdf) {
    .Call(`_pssst_rcpp_f_gengamma`, x, alpha, beta, gamma, log_pdf)
}

rcpp_F_gompertz <- function(x, rate, shape, lower_tail, give_log) {
    .Call(`_pssst_rcpp_F_gompertz`, x, rate, shape, lower_tail, give_log)
}

rcpp_F_loglogistic <- function(x, shape, scale, lower_tail, give_log) {
    .Call(`_pssst_rcpp_F_loglogistic`, x, shape, scale, lower_tail, give_log)
}

rcpp_f_loglogistic <- function(x, shape, scale, give_log) {
    .Call(`_pssst_rcpp_f_loglogistic`, x, shape, scale, give_log)
}

rcpp_F_dagum <- function(x, shape1, shape2, scale, lower_tail, give_log) {
    .Call(`_pssst_rcpp_F_dagum`, x, shape1, shape2, scale, lower_tail, give_log)
}

rcpp_f_dagum <- function(x, shape1, shape2, scale, give_log) {
    .Call(`_pssst_rcpp_f_dagum`, x, shape1, shape2, scale, give_log)
}

rcpp_f_gompertz <- function(x, rate, shape, give_log) {
    .Call(`_pssst_rcpp_f_gompertz`, x, rate, shape, give_log)
}

rcpp_hazard_integral <- function(lower_bound, upper_bound, log_shape, log_scale_vec, dist, breakpoints) {
    .Call(`_pssst_rcpp_hazard_integral`, lower_bound, upper_bound, log_shape, log_scale_vec, dist, breakpoints)
}

rcpp_turnbull <- function(niter, t0, t1, lefttrunc, righttrunc, weights, set_lower, set_upper) {
    .Call(`_pssst_rcpp_turnbull`, niter, t0, t1, lefttrunc, righttrunc, weights, set_lower, set_upper)
}

